[package]
name = "wbs-backup"
version = "0.0.0"
authors = [ "James Pharaoh <james@wellbehavedsoftware.com>" ]

[[bin]]
name = "backup-daemon"

[dependencies]
rustc-serialize = "0.2"

[dependencies.time]
git = "https://github.com/rust-lang/time"
